### ISSUE TITLE
Páginas de estados: Arreglar la distribución de elementos de la página

### ISSUE THREAD

**Issue by ponentesincausa** [CodeandoMexico/covid-estados#13]
Arreglar los elementos de la página para que la composición esté de acuerdo con el mockup:

- [ ] Añadir a componente para que no esté pegado a la orilla.
- [ ] Corregir botón de "sitio web oficial" para que esté en una línea.
- [ ] Corregir margen de los teléfonos.
- [ ] Corregir tamaños de textos en la sección.

Repo:
![image](https://user-images.githubusercontent.com/8941178/84550674-d67e5500-acd0-11ea-88c4-c431c52be443.png)

Mockup:
![image](https://user-images.githubusercontent.com/8941178/84550781-28bf7600-acd1-11ea-87c7-837c4b2edde9.png)

**Comment by almarngl** [comment]
Agregar: Arreglar typos y signos de interrogación en `Te interesa información sobre otro estado`

**Comment by RodolfoFerro** [comment]
- Añadir a componente para que no esté pegado a la orilla.
- Corregir botón de "sitio web oficial" para que esté en una línea.
- Corregir margen de los teléfonos.
- Corregir tamaños de textos en la sección.

<img width="1280" alt="Screen Shot 2020-06-16 at 1 37 11 PM" src="https://user-images.githubusercontent.com/8453749/84814093-92dc6180-afd6-11ea-9232-5afc45961739.png">

**Comment by josellausas** [comment]
@RodolfoFerro comenzando a trabajar en este issue

**Comment by josellausas** [comment]
Avances en branch `13-estado-detail-styles`

- [x] Estado Header Styles

<img width="509" alt="Screen Shot 2020-06-16 at 8 12 23 PM" src="https://user-images.githubusercontent.com/4162671/84843697-385ef780-b00e-11ea-8b9f-5852cc793810.png">

**Comment by almarngl** [comment]
@josellausas ¿cómo vas con este issue? ¿pudiste avanzar algo más? :D

**Comment by josellausas** [comment]
@almarngl estoy inundado de trabajo por el momento, el avance está en el branch `13-estado-detail-styles` , podría alguien retomar este issue? Tengo que entregar una app para el lunes y no creo poder avanzarle el fin de semana. :(
