### ISSUE TITLE
Medidas oficiales

### ISSUE THREAD

**Issue by ajd01** [CodeandoMexico/covid-estados#3]
Mostrar la información de medidas-01 en la sección de Medidas oficiales.

https://github.com/CodeandoMexico/covid-estados/blob/master/src/Detail/index.js#L94

**Comment by almarngl** [comment]
Mostrar la información de medidas-01, medidas-02 y medidas-03 en la sección de `Medidas Oficiales` 

Mockup: ![Captura de pantalla 2020-06-12 a la(s) 4 54 52 p m](https://user-images.githubusercontent.com/24925852/84549396-7b972e80-accd-11ea-806e-3628e2e3547e.png)

Base de datos: https://airtable.com/invite/l?inviteId=invfzG1hW4F9N8ifv&inviteToken=87bf96aa4651879b76dd0c5b4cd8021975c7a01b6118d5dd11372a45dc45de7e

**Comment by almarngl** [comment]
Ya está la conexión a la base, sólo hace falta que tanto el `nivel de riesgo` como la `tendencia`cambien el color de acuerdo al valor
