### ISSUE TITLE
Agregar Google Analytics

### ISSUE THREAD

**Issue by ponentesincausa** [CodeandoMexico/covid-estados#36]
Agregar Google Analytics tag al head / body

**Comment by ponentesincausa** [comment]
@almarngl danos un tag

**Comment by almarngl** [comment]
Va el tag:


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-170809396-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-170809396-1');
</script>

**Comment by Yarov** [comment]
El PR de esta issue está listo no se olviden de actualizar antes develop para que el PR quede solo con los cambios de GA

**Comment by RodolfoFerro** [comment]
@almarngl Este issue ya quedó, ¿nos confirmas si hay movimiento en el Analytics? 🙏

**Comment by RodolfoFerro** [comment]
Súper @Yarov ya nos ayudó y ya quedó.

<img width="1010" alt="Screen Shot 2020-07-03 at 12 30 57 PM" src="https://user-images.githubusercontent.com/8453749/86489166-17461880-bd29-11ea-8735-e677a107132a.png">

Cierro el issue.
