### ISSUE TITLE
Ajustar versión móvil para iPhone

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/covid-estados#39]
La versión móvil se ve perfectamente bien en Android, pero por alguna razón no se ve en iPhone. 

**Android**
<img width="35%" alt="photo_2020-06-24_19-49-27" src="https://user-images.githubusercontent.com/24925852/85641335-e3496400-b653-11ea-8483-9783f2c062eb.jpg"> <img width="35%" alt="photo_2020-06-24_19-49-32" src="https://user-images.githubusercontent.com/24925852/85641337-e47a9100-b653-11ea-893f-ce8a847f3e85.jpg">

*Iphone*
<img width="35%" alt="photo_2020-06-24_19-49-36" src="https://user-images.githubusercontent.com/24925852/85641348-ecd2cc00-b653-11ea-8779-3f7c57d236df.jpg"> <img width="35%" alt="photo_2020-06-24_19-49-38" src="https://user-images.githubusercontent.com/24925852/85641349-ee9c8f80-b653-11ea-82e6-2fc385223a0a.jpg">

**Comment by lopsum-animalpolitico** [comment]
Hola!

Esto es posible solucionarlo si se agrega un wrapper en App.js de la siguiente forma:

<img width="1091" alt="Captura de Pantalla 2020-07-06 a la(s) 11 50 06" src="https://user-images.githubusercontent.com/38991666/86618620-dba48c00-bf7e-11ea-8f09-e08d610d0424.png">

**Comment by RodolfoFerro** [comment]
¡Hola @lopsum-animalpolitico !

Noté que al añadir el wrapper se modifica un poco la vista principal, pues el footer no se queda fijo en bottom, ¿sabes qué corrección de estilo debemos añadir para ello? ¡Gracias!

**Comment by lopsum-animalpolitico** [comment]
Ya veo. Encontré otra solución (habría que quitar mi solución anterior).

Basta con envolver <div id="codeandocovid"> con otro div sin ninguna propiedad dentro de public/index.html:

<img width="362" alt="Captura de Pantalla 2020-07-06 a la(s) 14 15 41" src="https://user-images.githubusercontent.com/38991666/86630990-30ea9880-bf93-11ea-8339-0356aebed845.png">

**Comment by RodolfoFerro** [comment]
Creo que el problema ahora sería que la carpeta de `public` se genera cada vez que hacemos `npm run build`, entonces no sé si sea la mejor opción editarlo allí porque habría que editarlo en cada build. 🤔

**Comment by RodolfoFerro** [comment]
Hola @lopsum-animalpolitico , un update sobre esto es que intenté hacerlo desde `public/index.html` como sugieres y al parecer se rompe el deploy al GitHub Pages. 🤔
