### ISSUE TITLE
Ocultar el titulo Hazte la prueba en línea

### ISSUE THREAD

**Issue by ajd01** [CodeandoMexico/covid-estados#4]
Si todas las respuestas de prueba en linea por el estado son `no` deberíamos de ocultar ese titulo o mostrar alguna leyenda de que no hay información por el momento.

Arreglar el typo también 💯 
`Hazte la pruena en línea`

**Comment by almarngl** [comment]
Ya está el texto `no hay información por el momento` pero hay que ocultar la sección cuando no haya información
