### ISSUE TITLE
Agregar fechas de actualización de los datos

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/covid-estados#56]
Agregar fechas de actualización para dos secciones:
`Casos` : Se actualizan una vez al día 
`Semáforo`: Se actualiza cada lunes 8:00am

**Comment by Yarov** [comment]
¿Estas fechas se traen de algún lado? ó solo necesitamos que sean dinámicas a cada dia y hora mencionada.

**Comment by almarngl** [comment]
Hola @Yarov, sobre el tema de los `Casos`podemos jalar la fecha de aquí: https://github.com/mexicovid19/Mexico-datos/blob/master/datos/last_updated.csv 

Sobre `Semáforo`se saca de los informes de Gatell entonces sólo necesitaríamos que fuera dinámica, pero hoy anunciaron que no van a publicar semáforo por ahora :/ entonces dejemos este caso en pausa en lo que se define qué pasará con eso
