### ISSUE TITLE
Descargar un CSV con los datos

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/covid-estados#57]
Que en el botón de `Descargar datos`de la vista de estados se descargue un CSV en lugar de llevar a la versión pública de la tabla en Airtable

**Comment by RodolfoFerro** [comment]
Al parecer habrá que hacer un artilugio intermedio:
https://community.airtable.com/t/link-for-exporting-data-as-csv/23212/2

**Comment by RodolfoFerro** [comment]
Una opción es actualizar el respaldo del CSV que está en el repo cada que haya un cambio, y que sea esa la versión que se descarga. 🤔

**Comment by Yarov** [comment]
Se agrega el PR para la descarga del CSV

**Comment by RodolfoFerro** [comment]
Qué onda @Yarov , hice merge pero aún no he hecho deploy, aunque checa:
<img width="1280" alt="Screen Shot 2020-07-10 at 10 25 39 AM" src="https://user-images.githubusercontent.com/8453749/87171322-216f9600-c298-11ea-8b89-e0ae89c2cbc7.png">
Es de darle al botón. 🤔

**Comment by Yarov** [comment]
Ok, Reviso que onda con eso.

**Comment by Yarov** [comment]
@almarngl cuando puedas le das build, ya quedo listo esta parte

**Comment by almarngl** [comment]
Listo 🔥

**Comment by almarngl** [comment]
@Yarov voy viendo que descarga el CSV de casos, no el CSV de la tabla de Airtable :O
