### ISSUE TITLE
Transformar los teléfonos en links

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/covid-estados#63]
En la sección de `Líneas locales de atención` y la sección de `Violencia de Género`que los números sean links

**Comment by josellausas** [comment]
Estoy tratando de empujar mi branch con el enhancement pero me dice que no tengo permisos en el repo. Auida plz

**Comment by josellausas** [comment]
@almarngl PR listo: https://github.com/CodeandoMexico/covid-estados/pull/64

**Comment by RodolfoFerro** [comment]
Oh, no había notado que faltan los de la sección de `Violencia de género`, pero ya le dimos merge al #64 .

**Comment by josellausas** [comment]
https://github.com/CodeandoMexico/covid-estados/pull/65
