### ISSUE TITLE
Error 404 al usar link directo de un estado

### ISSUE THREAD

**Issue by josellausas** [CodeandoMexico/covid-estados#66]
Cuando se intenta accesar utilizando el link directo de un estado, aparece un error 404.

Como reproducir?
-------------------
Intentar usar el URL de un estado por ejemplo: https://directoriocovidmx.org/estado/veracruz
O, hacer refresh en la pagina de un estado.

<img width="1440" alt="Screen Shot 2020-07-09 at 6 09 32 PM" src="https://user-images.githubusercontent.com/4162671/87099441-5f74a780-c20f-11ea-8272-468e5c8a4157.png">

**Comment by Yarov** [comment]
@RodolfoFerro @almarngl  Para este bug recomiendo usar una plataforma de deploy como vercel para poder ese refresh y Github Pages no lo tendremos nunca ya que solo sirve páginas estáticas,

Solo hay que cambiar los dns y apuntar el dominio, si gustan los ayudo es muy sencillo y el servicio es gratuito.

**Comment by almarngl** [comment]
Uff, ya, pues me parece una buena solución @Yarov. @RodolfoFerro, ¿qué piensas tú?

**Comment by martinszy** [comment]
Lo pude reproducir, me imagino que quizás sea un error en el sistema que interpreta las rutas, no revisé el código todavía.

**Comment by josellausas** [comment]
@RodolfoFerro @Yarov hay alguna razon en particular por la cual estamos usando GitHub Pages? Entendido que github pages es para servir páginas estáticas, quizas no sea la mejor herramienta para servir un sitio dinámico con React. Encontré esto, donde dan una posible solución, pero quizas sea mejor utilizar algo que sea para servir sitios dinámicos: https://github.community/t/github-pages-reload-issue/10413

**Comment by RodolfoFerro** [comment]
Pues de hecho @Yarov nos estuvo apoyando con algunas pruebas en Vercel, @almarngl. Así que podríamos mudar el deploy para allá. Creo que de todos modos habría que dejar los accesos a CMX y configurar el deploy a los cambios del master. Así que no me parece mala opción si esto ayuda con la resolución de estos issues.

Lo otro es que hay que revisar el pricing, porque hay una versión free, al parecer, sin embargo no sé qué tanta limitante tenga en cuanto a recursos de cómputo/acceso del sitio. 🤔

**Comment by almarngl** [comment]
Vale, pues hagámoslo @Yarov @RodolfoFerro
