### ISSUE TITLE
Enlaces a app de estado erróneos en algunos estados

### ISSUE THREAD

**Issue by martinszy** [CodeandoMexico/covid-estados#69]
En algunos estados aparecen las apps con un enlace a  https://directoriocovidmx.org/estado/0

Ej:
![Captura de pantalla de 2020-07-10 22-10-03](https://user-images.githubusercontent.com/997732/87215237-311fc680-c2fa-11ea-8d35-329a1a6237a6.png)

**Comment by almarngl** [comment]
Listo, Martín, corregido. Era un detalle en la base :) ¡Muchas gracias!
