### ISSUE TITLE
Conectar columna de "Otros"

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/covid-estados#72]
La base de datos tiene una columna que se llama `Otros` que contiene otra información relevante que no entró dentro de las categorías principales. Se tiene que conectar esa columna a la sección de `Información relevante`. Tiene una estructura de diccionario, es decir, `texto: link, texto: link`. Tenemos que jalar el texto y ponerlo de título de la tarjeta, e integrar el link a la tarjeta como botón. 

Por el momento, pongamos el ícono de programas como la imagen de esa tarjeta.

**Comment by bifr0ns** [comment]
Alguien ya está trabajando en este issue?

**Comment by bifr0ns** [comment]
Mira, te anexo cómo quedaría, me avisas de cualquier cambio antes de hacer el PR.

Nota que los links de los teléfonos todos son como a teléfono normal, por ejemplo el de whatasapp no manda directo a wassap. Creo que se podría hacer de otra forma si es necesario 

Sonora: 
![imagen](https://user-images.githubusercontent.com/21296104/87567656-295d7a80-c68a-11ea-9102-4e03b100c615.png)

Aguascalientes:
![imagen](https://user-images.githubusercontent.com/21296104/87567720-3d08e100-c68a-11ea-863c-a341af99cd2c.png)

**Comment by almarngl** [comment]
Hola @bifr0ns, la idea es que fuera en una de las tarjetas pequeñas, como la de `Programas`o `Whatsapp`que tienes en tu primer screenshot. ¿Cómo ves? ¿O te parece que está mejor en las largas?

**Comment by bifr0ns** [comment]
Oh ya. Creo que los usuarios no ponen mucho el mouse en la tarjeta como para ver qué dice, entonces los links los podríamos dejar así con el título a la vista, y los teléfonos como tarjetas pequeñas, pero creo que se vería raro con el título largo en la parte de abajo. 
Alguna sugerencia?

**Comment by almarngl** [comment]
Vale, creo que es buena solución. Hagámoslo de esa manera

**Comment by bifr0ns** [comment]
Cómo ves así? O en el teléfono lo quito del texto?

Aguascalientes:
![imagen](https://user-images.githubusercontent.com/21296104/87582759-7d735980-c6a0-11ea-9547-181369efd4c5.png)

BCS:
![imagen](https://user-images.githubusercontent.com/21296104/87582829-9714a100-c6a0-11ea-9842-69d54612529f.png)

Sonora: 
![imagen](https://user-images.githubusercontent.com/21296104/87582862-a562bd00-c6a0-11ea-8d25-d60994e952ec.png)

Yucatán:
![imagen](https://user-images.githubusercontent.com/21296104/87582905-b4496f80-c6a0-11ea-8b15-c76efbff2686.png)

**Comment by almarngl** [comment]
Creo que si funciona como un link que te muestra el teléfono, podríamos quitarlo. Ahí el único detalle es que quizá debamos ordenarlos con un grid con máximo tres por línea, porque si no creo que justo empieza a haber problemas con las proporciones de la imagen de a lado. Pero se ve súper bien :)

**Comment by bifr0ns** [comment]
De hecho el detalle que comentas pasa con Yucatán con los programas adicionales, se salen de la página cuando son 4 y si empiezas a hacer la pantalla más pequeña

**Comment by almarngl** [comment]
Ah, buen punto, sí. ¿Entonces te parece que le pongamos el límite de tres por línea? Así justo no vamos a sacarlo de proporción

**Comment by bifr0ns** [comment]
Me parece bien tres. Por cierto creo que eso es mejor como otro issue, y ya subo esto de una vez.

**Comment by almarngl** [comment]
Va, me parece
