### ISSUE TITLE
Landing: Nombres de estados con mayúsculas y acentos correctos

### ISSUE THREAD

**Issue by ponentesincausa** [CodeandoMexico/covid-estados#8]
En el select de los estados, los nombres de los estados están todo en minúsculas. Cambiarlos a letra inicial mayúsculas y agregar acentos.

Ejemplo: "nuevo leon" cambiar a "Nuevo León"

![image](https://user-images.githubusercontent.com/8941178/84549321-53a7cb00-accd-11ea-9ea3-d074cbb4d68e.png)

**Comment by almarngl** [comment]
Fixed +1
